name: Latest Medium Blog Posts

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@1.8.6
        with:
          feed_list: "https://medium.com/feed/@arorakartik1589"
          max_post_count: 4
